### ISSUE TITLE
Readme suggestion

### ISSUE THREAD

**Issue by ijdickinson** [thefrontside/funcadelic.js#38]
I totally get that the aim of the readme is to demystify some FP concepts, and make the terminology more approachable. That's a great goal, and very worthwhile!

For me, however, some of the current language moves beyond playful into overdone. It could even be read as being somewhat patronising. Some examples:

- Looks pretty weird right? Exotic, even.
- A semi group is fancy name isn't it?
- extend it just teeeeeny weeeny bit further
- a unique, snowflake of an interface
- Are you tired of hearing about Functors? Well too bad! Because we're going to talk about them some more.

So my suggestion is to do a copy-editing pass through the readme, keep the overall tone of gentle introduction, but lose some of the more excessively flowery language.

Parenthetically, the George Clinton metaphor passed me by completely. Even having Googled him, I'm not quite sure what the point was you're making in that bit!

Hope this doesn't come across as too negative, these are suggestions for improvement, not intended as criticisms!

**Comment by taras** [comment]
@ijdickinson thank you for your feedback. 

> It could even be read as being somewhat patronising.

It's certainly not meant to be patronizing. The goal for this project is to make it approachable, but this README was also partially written in the context of some strong voices in JavaScript community who publicly mock functional programming terminology. 

> So my suggestion is to do a copy-editing pass through the readme, keep the overall tone of gentle introduction, but lose some of the more excessively flowery language.

Yeah, this is definitely a good suggestion at this point.

> Hope this doesn't come across as too negative, these are suggestions for improvement, not intended as criticisms!

No worries. Appreciate you taking the time to make suggestions.

Would you consider making a pass at the README and submit a PR with changes?

**Comment by ijdickinson** [comment]
@taras I'm just reviewing some old tickets, and I apologise but I've simply not had the time to work on this.
